num_concepts: 8
num_classes: 1
learning_rate: 0.001956
momentum: 0.9
weight_decay: 1.568e-05
criterion: MSELoss
optimizer: AdamW
model: nbm
model_params:
  nary: null
  num_bases: 100
  hidden_dims:
  - 256
  - 128
  - 128
  num_subnets: 1
  dropout: 0.0
  bases_dropout: 0.05
  batchnorm: true
  output_penalty: 0.0001439
trainer:
  gpus: 1
  num_nodes: 1
  max_epochs: 1000
  log_every_n_steps: 1
  strategy: ddp
datamodule:
  dataset:
    dataset_name: CaliforniaHousing
    scale_range:
    - 0
    - 1
  batch_size: 1024
  max_epochs: 1000
  timeout_min: 1440
  train_dataset_size: 14447
  val_dataset_size: 2065
  test_dataset_size: 4128
warmup: null
ckpt_dir: /home/amaya.dharmasiri/nbm-spam/multirun/2022-08-15/19-40-33/0
